on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
  
jobs:
  build:
    name: build
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
